import { NextUIProvider } from "@nextui-org/system"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NextUIProvider>
      <body>{children}</body>
      </NextUIProvider>
    </html>
  )
}
